/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#dce9ff",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c8c5d0",
        "surface-container-highest": "#d3e4fe",
        "surface": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "on-secondary-container": "#fffbff",
        "outline": "#787680",
        "on-tertiary-fixed-variant": "#4a3d7c",
        "primary-fixed": "#e3dfff",
        "on-primary-fixed-variant": "#444173",
        "on-secondary-fixed-variant": "#5a00c6",
        "error": "#ba1a1a",
        "tertiary": "#0c0034",
        "secondary-fixed-dim": "#d2bbff",
        "tertiary-container": "#241554",
        "on-tertiary-fixed": "#1e0e4e",
        "background": "#f8f9ff",
        "on-tertiary-container": "#8d7fc3",
        "on-background": "#0b1c30",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e7deff",
        "surface-container-low": "#eff4ff",
        "secondary-container": "#8a4cfc",
        "secondary": "#712ae2",
        "on-secondary": "#ffffff",
        "primary": "#070235",
        "on-surface": "#0b1c30",
        "primary-container": "#1e1b4b",
        "inverse-on-surface": "#eaf1ff",
        "on-error-container": "#93000a",
        "surface-dim": "#cbdbf5",
        "surface-container": "#e5eeff",
        "on-primary-fixed": "#181445",
        "secondary-fixed": "#eaddff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#47464f",
        "tertiary-fixed-dim": "#ccbeff",
        "inverse-primary": "#c4c1fb",
        "on-primary-container": "#8683ba",
        "primary-fixed-dim": "#c4c1fb",
        "on-error": "#ffffff",
        "inverse-surface": "#213145",
        "surface-tint": "#5b598c",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#25005a",
        "brand-indigo": "#070235",
        "brand-violet": "#712ae2",
        "brand-surface": "#f8f9ff",
        "brand-on-surface": "#0b1c30",
        "brand-on-surface-variant": "#47464f",
        "brand-outline": "#787680",
        "brand-outline-variant": "#c8c5d0",
        "brand-violet-container": "#8a4cfc",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "brand": "1rem",
        "brand-sm": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "64px",
        "section-padding-mobile": "64px",
        "gutter": "24px",
        "stack-md": "32px",
        "base": "8px",
        "stack-sm": "16px",
        "section-padding-desktop": "120px",
        "container-max": "1280px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'brand-low': '0 4px 20px rgba(30,27,75,0.04)',
        'brand-high': '0 8px 30px rgba(30,27,75,0.08)',
      }
    },
  },
  plugins: [],
}
