# Generated by Django 4.2.9 on 2026-05-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_start', models.DateTimeField(auto_now_add=True)),
                ('scan_end', models.DateTimeField(blank=True, null=True)),
                ('emails_scanned', models.IntegerField(default=0)),
                ('subscriptions_found', models.IntegerField(default=0)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'email_scan_logs',
                'ordering': ['-scan_start'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('email_sender', models.EmailField(max_length=254)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('billing_frequency', models.CharField(default='monthly', max_length=50)),
                ('category', models.CharField(choices=[('saas', 'SaaS / Logiciel'), ('streaming', 'Streaming'), ('newsletter', 'Newsletter'), ('hosting', 'Hébergement'), ('marketing', 'Marketing'), ('design', 'Design'), ('productivity', 'Productivité'), ('other', 'Autre')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('cancelled', 'Annulé'), ('to_review', 'À vérifier')], default='to_review', max_length=20)),
                ('first_detected_date', models.DateField()),
                ('last_billing_date', models.DateField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-monthly_cost', '-created_at'],
            },
        ),
    ]
